### ISSUE TITLE
Unselecting a requirement shifts the content of the decision table 

### ISSUE THREAD

**Issue by talbendavid** [PeerSay/Atlas#156]
If I unselect a requirement, it is removed from the decision table 
However the content of the row in the table remains and is now associated with the row that used to be below it.

To reproduce:
Create a project, choose one product and 3 requirements.
Go to the decision table and assign distinct values in all editable fields (weight, description, grade) for easy identification.

Now go back to the Criteria page and unselect the second criteria of the three (the middle one).
Go to the decision table, and you will see that the values of the deleted requirement remain in the second row, although it is now actually reflecting the last requirement (i.e. the weight description and grade of the removed requirement are now associated with the one that used to be after it).

Note:
I believe that a solution to this should consider issue #145. 
Similarly to unselecting a product, it should also be possible to unselect and reselect a requirement without losing the data already entered.

**Comment by talbendavid** [comment]
When selecting a requirement the application crashes.
Reproduced on private and on staging.
Here is the exception (from my private instance):

[API] Patching project[Cp01U8Ee] for user=[tal.bendavidd@gmail.com] with [{"op":"add","path":"/requirements/0","value":{"_id":"559cf8fcd21e2f6d44eb640f","name":"Price","category":"","popularity":99,"topic":"Cost","description":"How much this solution cost. Monthly / Annually / or one time payment.","selected":true}}]
C:\Users\HP-PC\Development\Atlas\app\models\projects.js:279
                    var oldCol = _.findWhere(oldRow.products, {prodId: col.pro
                                                   ^
TypeError: Cannot read property 'products' of undefined
    at C:\Users\HP-PC\Development\Atlas\app\models\projects.js:279:52
    at Function.forEach (C:\Users\HP-PC\Development\Atlas\node_modules\lodash\dist\lodash.js:3298:15)
    at C:\Users\HP-PC\Development\Atlas\app\models\projects.js:274:15
    at Function.forEach (C:\Users\HP-PC\Development\Atlas\node_modules\lodash\dist\lodash.js:3298:15)
    at buildNewTable (C:\Users\HP-PC\Development\Atlas\app\models\projects.js:265:7)
    at model.ensureTableConsistency (C:\Users\HP-PC\Development\Atlas\app\models\projects.js:229:20)
    at _next (C:\Users\HP-PC\Development\Atlas\node_modules\mongoose\node_modules\hooks\hooks.js:50:30)
    at fnWrapper (C:\Users\HP-PC\Development\Atlas\node_modules\mongoose\node_modules\hooks\hooks.js:159:8)
    at model.ensureStubsUpdated (C:\Users\HP-PC\Development\Atlas\app\models\projects.js:192:48)
    at _next (C:\Users\HP-PC\Development\Atlas\node_modules\mongoose\node_modules\hooks\hooks.js:50:30)
    at fnWrapper (C:\Users\HP-PC\Development\Atlas\node_modules\mongoose\node_modules\hooks\hooks.js:159:8)
    at model.ensureTitle (C:\Users\HP-PC\Development\Atlas\app\models\projects.js:180:59)
    at _next (C:\Users\HP-PC\Development\Atlas\node_modules\mongoose\node_modules\hooks\hooks.js:50:30)
    at fnWrapper (C:\Users\HP-PC\Development\Atlas\node_modules\mongoose\node_modules\hooks\hooks.js:159:8)
    at complete (C:\Users\HP-PC\Development\Atlas\node_modules\mongoose\lib\document.js:994:5)
    at C:\Users\HP-PC\Development\Atlas\node_modules\mongoose\lib\document.js:985:20
27 Aug 11:05:37 - [nodemon] app crashed - waiting for file changes before starting...
